### ISSUE TITLE
Upload von Kartenbildern

### ISSUE THREAD

**Issue by bootyeaterboy** [iptch/g_collection_be#1]
Wir benötigen die Kartenbilder im Azure Bucket card-high-res-images, siehe [hier](https://portal.azure.com/#@iptzug.onmicrosoft.com/resource/subscriptions/da12d467-03ae-4675-aa29-d3b26fdbd2cc/resourceGroups/rg-genius-collection/providers/Microsoft.Storage/storageAccounts/gcollection/containersList). Dabei handelt es sich um alle (zukünftigen) ipt-ler:innen. Die Bilder sollen im jpg Format sein. Benannt sind die Bilder mit dem Kürzel des jeweiligen Mitarbeitenden in Kleinbuchstaben, z.B. kdu.jpg. Als Quelle können die ipt Website oder das HR Tool (für die Neuen) verwendet werden.

Akzeptanzkriterien:
- Von jeder ipt-lerin und jedem ipt-ler ist ein Bild im Bucket enthalten.
- Die Bilder sind in Form von <Kürzel>.jpg abgelegt.

Links:
- #2

**Comment by iischwuerfl** [comment]
Der initiale Bildupload wurde manuell durchgeführt:

- Quelle: https://drive.google.com/drive/folders/1AIsFSlE1uGmrLhxvvZDl336nnYXe-aek
- Renaming von allen Files -> <kürzel>.jpg
- Upload in Storage: [card-high-res-images](https://portal.azure.com/#view/Microsoft_Azure_Storage/ContainerMenuBlade/~/overview/storageAccountId/%2Fsubscriptions%2Fda12d467-03ae-4675-aa29-d3b26fdbd2cc%2FresourceGroups%2Frg-genius-collection%2Fproviders%2FMicrosoft.Storage%2FstorageAccounts%2Fgcollection/path/card-high-res-images/etag/%220x8DBB05FD583A1D8%22/defaultEncryptionScope/%24account-encryption-key/denyEncryptionScopeOverride~/false/defaultId//publicAccessVal/None)


Prozess, um neue Bilder (von Newstartern oder aktualisierte Bilder)

- Upload vom Bild (<kürzel>.jpg) in Storage: [card-high-res-images](https://portal.azure.com/#view/Microsoft_Azure_Storage/ContainerMenuBlade/~/overview/storageAccountId/%2Fsubscriptions%2Fda12d467-03ae-4675-aa29-d3b26fdbd2cc%2FresourceGroups%2Frg-genius-collection%2Fproviders%2FMicrosoft.Storage%2FstorageAccounts%2Fgcollection/path/card-high-res-images/etag/%220x8DBB05FD583A1D8%22/defaultEncryptionScope/%24account-encryption-key/denyEncryptionScopeOverride~/false/defaultId//publicAccessVal/None)

**Comment by iischwuerfl** [comment]
@weber-chris magst du noch ergänzen? Können wir das Ticket schliessen?

**Comment by weber-chris** [comment]
LGTM
