### ISSUE TITLE
Logik zur Kartengenerierung via Endpunkt

### ISSUE THREAD

**Issue by bootyeaterboy** [iptch/g_collection_be#10]
Akzeptanzkriterien
- Funktion, die aufgerufen werden kann, um für einen bestimmen User in der DB n zufällige Karten mit m Dubletten zu generieren.
- Wenn Anzahl Dubletten nicht definiert wird, ist die Auswahl komplett zufällig

BE:
- #9
- #12

**Comment by risvele** [comment]
Funktionalität umgesetzt und mit PR https://github.com/iptch/g_collection_be/pull/38 gemergt.
Mit Testing angefangen, jedoch nicht ganz fertig geworden. Arbeiten sind im branch 'test-assign-ownership' gepusht.
