### ISSUE TITLE
Sortierfunktion für Karten via Dropdown

### ISSUE THREAD

**Issue by bootyeaterboy** [iptch/g_collection_be#11]
Benutzer:innen sollen in der Cards Komponente die Karten sortieren können mittels Dropdown rechts vom Titel "Chärtli". Nach folgenden Attributen soll gefiltert werden können:
- Erhalt Karte (bei doppelten Karten ist das Datum der zuletzt erhaltenen Karte relevant)
- Kürzel (Alphabet)
- Vorname und Nachname (Alphabet)
- Anzahl Dubletten

Akzeptanzkriterien:
- Benutzer:innen können ihre Karten nach obigen Attributen sortieren.
- Das Sortieren funktioniert sowohl bei der Ansicht aller Karten als auch der Ansicht der Karten, die man besitzt.

BE:
- #13

**Comment by Kildrese** [comment]
[Pull Request Draft](https://github.com/iptch/g-collection-fe/pull/9) schon erstellt, warten noch quantity variable aus dem backend um dann auch dort last_received als variable hinzuzufügen für die Sorting Option

**Comment by Sergensen** [comment]
BE draft ist hier: https://github.com/iptch/g_collection_be/pull/34
Sollte fertiggestellt werden, sobald der quantity code ready ist.
