### ISSUE TITLE
Sortierfunktion für Karten im cards Endpunkt

### ISSUE THREAD

**Issue by bootyeaterboy** [iptch/g_collection_be#13]
Sortieren der Cards basierend auf Query-Parameter.

Akzeptanzkriterien:
- Sortierbar basierend auf:
  - Erhalt Karte
  - Kürzel 
  - Vorname
  - Nachname
  - Anzahl Dubletten

FE: 
- #11

**Comment by nevius** [comment]
Könnte man auch direkt im Frontend machen. Bessere Performance und weniger Aufwand :)

**Comment by makuche** [comment]
Closed, wird mit #11 im Frontend umgesetzt
