### ISSUE TITLE
Aufruf Tausch-Endpunkt beim Scannen eines QR Codes

### ISSUE THREAD

**Issue by bootyeaterboy** [iptch/g_collection_be#14]
Eine Karten-Transaktion verläuft wie folgt:
1. Scan des QR Codes vom Smartphone des "Givers"
2. Aufruf des BE-Endpunkt (siehe verlinkte Tickets unten"
3. Redirect zur neu erhaltenen Karte

Akzeptanzkriterien:
- Benutzer:innen können Karte mittels QR Code weitergeben.

BE:
- #17
- #15

**Comment by brathis** [comment]
Status: Funktionierende Implementierung, braucht noch ein wenig Cleanup
