### ISSUE TITLE
Tausch-Endpunkt erstellen

### ISSUE THREAD

**Issue by weber-chris** [iptch/g_collection_be#17]
Endpunkt welcher vom FE aufgerufen wird, sobald ein QR Code gescannt wurde.
1. Überprüfen, ob der OTP mit dem in der DB hinterlegten OTP übereinstimmt
2. Falls ja,  den Card Owner auf den neuen Owner wechseln
3. OTP in der DB löschen
4. Antwort ob erfolgreich oder nicht
FE: #14

**Comment by ovanov** [comment]
Everything is implemented, except the OTP check. The [PR](https://github.com/iptch/g_collection_be/pull/39) is open and needs to be merged.
