### ISSUE TITLE
Erstellung Zusammenfassungs-Endpunkt

### ISSUE THREAD

**Issue by weber-chris** [iptch/g_collection_be#18]
Aggregiert Informationen zu
* Wieviele Karten ich habe, wieviele davon Dubletten sind
* Wieviele Karten total existieren, wieviele davon Dubletten sind
* Gesamte Rangliste
* Mein eigener Rang

Akzeptanzkriterien:
- Dem Frontend werden alle obigen Infos über einen Endpunkt zur Verfügung gestellt.

FE
- #19

**Comment by ManuelSzecsenyi** [comment]
Wartet auf merge von hier: https://github.com/iptch/g_collection_be/pull/37

**Comment by weber-chris** [comment]
looks good - merged.
