### ISSUE TITLE
Erstellung eines geilen Welcome-Screen-Dashboards

### ISSUE THREAD

**Issue by bootyeaterboy** [iptch/g_collection_be#19]
Den "Zusammenfassungs-Endpunkt" aufrufen und die Infos ansprechend im Welcome-Screen-Dashboard anzeigen. Bei den Infos handelt es sich um den eigenen Fortschritt und den Stand des Spiels (z.B. Rangliste, Karten im Umflauf, ...). Aktuell sind einfach statische Mock-Daten hinterlegt.

Akzeptanzkriterien
- Im Welcome-Screen-Dashboard werden die Daten des Zusammenfassungs-Endpunks visualisiert.

BE:
- #18

**Comment by ManuelSzecsenyi** [comment]
Mit BE von hier abgestimmt und merged: https://github.com/iptch/g_collection_be/pull/37
Durch Änderungen der anderen kann es noch zu kleinen Änderungen kommen

**Comment by weber-chris** [comment]
backend gemerged. looks good
