### ISSUE TITLE
Kartenbilder Thumbnail Creator

### ISSUE THREAD

**Issue by weber-chris** [iptch/g_collection_be#2]
Aus Performancegründen werden an verschiedenen Stellen kleine Thumbnailbilder von den Kartenbildern benötigt, z.B. in der Übersicht aller vorhandenen Karten. Um diese Thumbnails nicht händisch erstellen zu müssen, soll eine Azure Funktion (oder analoge Funktionalität in Azure) benutzt werden, welche auf den Event hört, der gefeuert wird, sobald ein neues Bild im Storage Account Container hochgeladen wird. Dieses Bild wird dann verkleinert und in einem anderen Container abgelegt.
* Storage-Account: [gcollection](https://portal.azure.com/#@iptzug.onmicrosoft.com/resource/subscriptions/da12d467-03ae-4675-aa29-d3b26fdbd2cc/resourceGroups/rg-genius-collection/providers/Microsoft.Storage/storageAccounts/gcollection/containersList)
* Quell-Container: card-high-res-images
* Ziel-Container: card-thumbnails

**Akzeptanzkriterien**
* Neue Bilder werden als Thumbnail generiert, sobald sie im Quell-Container hinterlegt werden
* Wenn Bilder geändert oder gelöscht werden, werden die Änderungen/Löschung auch auf den Thumbnails nachgezogen.

Links:
- #1

**Comment by bruggisser** [comment]
First approach here: https://github.com/iptch/g_collection_be/tree/2-kartenbilder-thumbnail-creator
Function name: gcollection-thumbnail-creator
Add connection string to configuration with name "connectionstring".
