### ISSUE TITLE
Aufruf vom Endpunkt zur Initialen Usererstellung

### ISSUE THREAD

**Issue by weber-chris** [iptch/g_collection_be#20]
Beim Laden der Page nach dem Login, soll innerhalb der Funktion `this.msalBroadcastService.inProgress$.subscribe()` der Endpunkt für die initiale Usererstellung aufgerufen werden, der den User erstellt falls nötig.

Akzeptanzkriterien:
- Beim Start jeder Session wird initialUserSetup aufgerufen

BE:
- #12

**Comment by iischwuerfl** [comment]
Erst nachdem dieser Aufruf erfolgreich war, sollen die anderen Endpoints (/cards etc) aufgerufen werden

**Comment by nevius** [comment]
PR: https://github.com/iptch/g-collection-fe/pull/5
