### ISSUE TITLE
Erweiterung Cards-Endpunkte mit der Kartenanzahl

### ISSUE THREAD

**Issue by bootyeaterboy** [iptch/g_collection_be#21]
Es braucht bei den Cards-Endpunkten ein zusätzliches Attribut "owned" (Integer), das dem Frontend sagt, wie oft die Benutzerin die Karte besitzt. 

Akzeptanzkriterien:
- Die Endpunkte /cards und /cards/:id retournieren das Attribut "owned".

FE:
- #22

**Comment by selimkaelin** [comment]
Done. Filtering is done by card object and user id. Allows for both endpoints /cards/ and /cards/:id to work.
