### ISSUE TITLE
Erweiterung Detailansicht einer Karte

### ISSUE THREAD

**Issue by ihaveamicroservice** [iptch/g_collection_be#22]
Wenn bei einer Karte das Attribut "owned" auf 0 ist (die Benutzerin hat die Karte nicht), werden nur folgende Informationen in der Detailansicht angezeigt:
- Name
- Rolle
- Bild in schwarzweiss

Wenn bei der Anzeige aller Karten bei einer Karte das Attribut "owned" auf 0 ist, soll die Karte in schwarzweiss angezeigt werden.

Akzeptanzkriterien:
- Detailansicht (/cards/:id): Benutzer:innen sehen nicht alle Infos einer Karte, die sie nicht besitzen. Zudem ist das Bild in schwarzweiss.
- Kartenübersicht (/cards): Benutzer:innen sehen Karten, die sie nicht besitzen, in schwarzweiss.

BE:
- #21

**Comment by DominiqueHeyn** [comment]
PRs:
https://github.com/iptch/g-collection-fe/pull/4
https://github.com/iptch/g-collection-fe/pull/7
