### ISSUE TITLE
Definition und Eintreibung von Infos auf Karten

### ISSUE THREAD

**Issue by bootyeaterboy** [iptch/g_collection_be#3]
Zur Orientierung: Daten von Genius Collection v1: https://drive.google.com/drive/folders/1MXabJXvp-bhkJcBqp4PZQzQ8DSuER6n1

Akzeptanzkriterien:
- Definieren der Infos/Funfacts, die über die User gesammelt und im Spiel angezeigt werden sollen
- Erstellen eines Google Forms, welches diese Infos abholt und in ein GSheet speichert

Links: 
- #8

**Comment by weber-chris** [comment]
Temporär an mich assigned, bis Larissa den User verknüpfen kann.

**Comment by weber-chris** [comment]
Infos und GSheet stehen. Jedoch unklar, ob diese Daten via Gsheet reinkommen sollen.

**Comment by weber-chris** [comment]
https://drive.google.com/drive/folders/1YMGI14RqB4KfAd6qagBRNK-XmtVHJcra

**Comment by weber-chris** [comment]
Daten werden gesammelt, Grossteil der ipt hat es bereits ausgefüllt.
