### ISSUE TITLE
Persönliche Informationen im Profil editieren

### ISSUE THREAD

**Issue by DominiqueHeyn** [iptch/g_collection_be#33]
Als iptlerIn möchte ich die Fun-Facts die auf meiner Karte stehen in meinem Profil einsehen und editieren können.

Akzeptanzkriterien:

- Die Felder, die in https://github.com/iptch/g_collection_be/issues/3 definiert wurden können auf der Profil-Seite für die eigene Karte eingesehen werden
- Die Felder sind editierbar und Änderungen werden in der Datenbank persistiert

**Comment by weber-chris** [comment]
Aufgesplittet
