### ISSUE TITLE
Pagination für /cards

### ISSUE THREAD

**Issue by bootyeaterboy** [iptch/g_collection_be#4]
Siehe https://www.django-rest-framework.org/api-guide/pagination/

Akzeptanzkriterien:
- /cards implementiert Django Pagination 

FE:
- #6

**Comment by nevius** [comment]
Könnte man direkt nur im Frontend machen. Weniger Aufwand und bessere Performance :)

**Comment by bootyeaterboy** [comment]
Sweet, go for it @nevius! 👍
