### ISSUE TITLE
Filterfunktion für /cards Endpunkt 

### ISSUE THREAD

**Issue by weber-chris** [iptch/g_collection_be#5]
Cards können via Query-Parameter gefiltert werden.

Akzeptanzkriterien:
- Filterfunktion für owner via Query Parameter (Retourniert nur Cards, wo Owner == User ist)

Links:
- #6

**Comment by nevius** [comment]
Könnte man auch direkt im Frontend machen. Bessere Performance und weniger Aufwand :)

**Comment by bootyeaterboy** [comment]
Wie würdest du das machen @nevius? Für jede Karte alle Benutzer mitgeben, die sie besitzen?

**Comment by nevius** [comment]
@bootyeaterboy Nein stimmt in diesem Fall macht es sinn ein Endpoint zu machen. Jenny ist schon dran :)

**Comment by iischwuerfl** [comment]
@bootyeaterboy wir (Philipp und ich) haben dies nochmals diskutiert:

/cards gibt nach Implementierung von https://github.com/iptch/g_collection_be/issues/21 alle nötigen Infos zurück (inkl owned = 0 oder > 0 ), so dass dies im Frontend gefiltert werden kann. D.h. der zusätzliche Endpoint im Backend macht unserer Meinung nach keinen Sinn.
