### ISSUE TITLE
Datenbankbeladung für Karteninfos via Google Sheet

### ISSUE THREAD

**Issue by bootyeaterboy** [iptch/g_collection_be#8]
Akzeptanzkriterien:
- Ein regelmässiger Job/Azure Funktion liest das gesamte durch Google Forms generierte Google Sheet
- Pro unique Emailadresse wird 1 Eintrag in der Datenbank Eintrag beschrieben. Falls >1 Eintrag besteht, wird die neuste Information verwendet

Links:
- #3

**Comment by cyber-moon** [comment]
New repo for utilities (azure functions etc):
https://github.com/iptch/g_collection_util

**Comment by cyber-moon** [comment]
Status:
- GDrive-Access Key stored in vault and used for fetching data.
- Data is fetched every minute, and received dataframe is printed.
- Runs on my machine. Also deployed to azure, but couldn't see the logs.

Todo:
- Write dataframe to postgres-DB

More details: See README in github-repo

**Comment by weber-chris** [comment]
done via https://github.com/iptch/g_collection_mgmt/pull/1
good enough for v1
