### ISSUE TITLE
Geschützter Endpunkt für Kartengenerierung (Admin only)

### ISSUE THREAD

**Issue by bootyeaterboy** [iptch/g_collection_be#9]
Akzeptanzkriterien:
- User Object hat weiteres Attribut "is_admin"
- Beim Aufruf wird gecheckt, ob Caller Admin ist.
- Wenn Caller Admin ist, wird Logik zur Katengenerierung für jeden User getriggert, um X Karten zuzuweisen.

BE:
- #10

**Comment by risvele** [comment]
Status des Tickets: Wurde am HandsOn-ERFA nicht bearbeitet.

**Comment by weber-chris** [comment]
Done: https://github.com/iptch/g_collection_be/pull/45
